apiVersion: v1
kind: policy
metadata:
  name: allow-apub
spec:
  selector: stack == 'a' && cluster == 'public'
  order: 400
  ingress:
  - action: allow
    protocol: tcp
    source:
      selector: stack == 'a' && cluster == 'public'
      ports: [9999]
