apiVersion: v1
kind: Service
metadata:
  name: nc-pod-svc 
  labels:
    name: nc-pod-svc
    app: nc-pod
    version: 0.1.0
spec:
  type: NodePort
  # Optional - make the service headless by uncommenting the next line
  # clusterIp: None
  selector: 
    app: nc-pod
  ports:
  - name: nc-tcp-listener
    protocol: TCP
    port: 26500
    nodePort: 30250
