apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nc-pod 
  labels:
    name: nc-pod
    app: nc-pod
    version: 0.1.0
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nc-pod
        version: 0.1.0
        stack: a
        cluster: public
    spec:
      containers:
        - name: nc-pod
          image: quay.io/samsung_cnct/nc-pod:latest 
          env:
            - name: NC_CMD_ARGS
              value: "-l 9999"
            - name: STACK_CLUSTER
              value: "Pub A"
          ports:
          - containerPort: 9999
